spring.application.name=backend

# ==============================================================
# CONFIGURACIÓN DEL SERVIDOR
# ==============================================================
# Puerto donde se levantará nuestra API (Backend)
server.port=8080

# ==============================================================
# CONEXIÓN A LA BASE DE DATOS (PostgreSQL en Docker)
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5455/logictrack_db
spring.datasource.username=postgres
spring.datasource.password=rootpassword123
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==============================================================
# Muestra las consultas SQL en la terminal (muy útil para debuggear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 'update' creará las tablas automáticamente en esta fase de desarrollo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect